### ISSUE TITLE
Walk while in menu bug

### ISSUE THREAD

**Issue by BryBTG** [NequZ/esx_allrounddealer#1]
When you walk while the menu is open. The npc does not respond. 

Video link: https://streamable.com/zq0rr

**Comment by morpheause** [comment]
Try to insert "menuOpen = false" into line 50.

         if wasOpen then
               wasOpen = false
               menuOpen = false
               ESX.UI.Menu.CloseAll()
          end

**Comment by NequZ** [comment]
Yes after that it should work
